# Site settings
title: Jon's Coding Journey
header-img: img/home-bg.png
email: jonrberkowitz@gmail.com
copyright_name: JonRBerkowitz
description: > # this means to ignore newlines until "baseurl:"
  Starting from Scratch
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JonRBerkowitz
learn_profile: JonRBerkowitz
email_username: jonrberkowitz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
